#ifndef HAVE_DISAMBIGUATION_H
#define HAVE_DISAMBIGUATION_H 1

#include <iostream>

#include "proto-disambiguation.pb.h"

extern "C" {
#include "rgraph.h"
}

// precision for relatedness values (for rounding)
#define PRECISION 5

/**
 * This class is an extension of the DisambiguationRequest automatically generated by Protobuf. It
 * mainly adds a method for executing the disambiguation using a knowledge graph.
 */
class WSDDisambiguationRequest  : public DisambiguationRequest {
  
public:
  /**
   * Compute disambiguation for this request using the graph pointed to in the argument. Store
   * results in the ranking values of the entity candidates.
   */
  void disambiguation(rgraph *graph);


};


/**
 * Operator for writing to standard streams
 */
std::ostream& operator<<(std::ostream&, const WSDDisambiguationRequest&);

/**
 * Operator for reading from standard streams
 */
std::istream& operator>>(std::istream&, WSDDisambiguationRequest&);


#endif
